package com.pojo;

// Generated 22 Jun, 2019 12:15:44 PM by Hibernate Tools 3.4.0.CR1

/**
 * EBook generated by hbm2java
 */
public class EBook implements java.io.Serializable {

	private String callno;
	private String name;
	private String author;
	private String publisher;
	private Integer quantity;
	private Integer issued;

	public EBook() {
	}

	public EBook(String callno) {
		this.callno = callno;
	}

	public EBook(String callno, String name, String author, String publisher, Integer quantity, Integer issued) {
		this.callno = callno;
		this.name = name;
		this.author = author;
		this.publisher = publisher;
		this.quantity = quantity;
		this.issued = issued;
	}

	public String getCallno() {
		return this.callno;
	}

	public void setCallno(String callno) {
		this.callno = callno;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Integer getIssued() {
		return this.issued;
	}

	public void setIssued(Integer issued) {
		this.issued = issued;
	}

}
