package com.pojo;

// Generated 22 Jun, 2019 12:15:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * EIssuebook generated by hbm2java
 */
public class EIssuebook implements java.io.Serializable {

	private Integer issueid;
	private String callno;
	private Integer studentid;
	private String studentname;
	private String studentmobile;
	private Date issueddate;
	private String returnstatus;

	public EIssuebook() {
	}

	public EIssuebook(String callno, Integer studentid, String studentname, String studentmobile, Date issueddate,
			String returnstatus) {
		this.callno = callno;
		this.studentid = studentid;
		this.studentname = studentname;
		this.studentmobile = studentmobile;
		this.issueddate = issueddate;
		this.returnstatus = returnstatus;
	}

	public Integer getIssueid() {
		return this.issueid;
	}

	public void setIssueid(Integer issueid) {
		this.issueid = issueid;
	}

	public String getCallno() {
		return this.callno;
	}

	public void setCallno(String callno) {
		this.callno = callno;
	}

	public Integer getStudentid() {
		return this.studentid;
	}

	public void setStudentid(Integer studentid) {
		this.studentid = studentid;
	}

	public String getStudentname() {
		return this.studentname;
	}

	public void setStudentname(String studentname) {
		this.studentname = studentname;
	}

	public String getStudentmobile() {
		return this.studentmobile;
	}

	public void setStudentmobile(String studentmobile) {
		this.studentmobile = studentmobile;
	}

	public Date getIssueddate() {
		return this.issueddate;
	}

	public void setIssueddate(Date issueddate) {
		this.issueddate = issueddate;
	}

	public String getReturnstatus() {
		return this.returnstatus;
	}

	public void setReturnstatus(String returnstatus) {
		this.returnstatus = returnstatus;
	}

}
