package com.pojo;

// Generated 22 Jun, 2019 12:15:44 PM by Hibernate Tools 3.4.0.CR1

/**
 * ELibrarian generated by hbm2java
 */
public class ELibrarian implements java.io.Serializable {

	private Integer id;
	private String name;
	private String password;
	private String email;
	private String mobile;

	public ELibrarian() {
	}

	public ELibrarian(String name, String password, String email, String mobile) {
		this.name = name;
		this.password = password;
		this.email = email;
		this.mobile = mobile;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

}
